---
title: "Types and Tokens for each Sub-Corpora"
author: "Sitler"
date: "2025-04-30"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(tidyr)
library(gt)

lb_data <- read.csv("lb_info.csv")

corpus_info <- read.csv("~/Statistics Practice/lb_info.csv") %>%
  select(Sub.Corpus, Total.Tokens, Total.Files) %>%
  distinct(Sub.Corpus, .keep_all = TRUE) %>%
  mutate(
    Total.Tokens = as.numeric(gsub("[^0-9.]", "", Total.Tokens)),
    Tokens.Per.File = Total.Tokens / Total.Files
  )

avg_tokens <- corpus_info %>%
  group_by(Sub.Corpus) %>%
  summarise(Average.Tokens.Per.File = mean(Tokens.Per.File, na.rm = TRUE))

corpus_info <- left_join(corpus_info, avg_tokens, by = "Sub.Corpus")

corpus_info

```



```{r}
ordered_levels <- c("J-WE", "J-SM", "ENS-WE", "ENS-SM")

wide_table <- corpus_info %>%
  filter(Sub.Corpus %in% ordered_levels) %>%
  mutate(Sub.Corpus = factor(Sub.Corpus, levels = ordered_levels)) %>%
  select(Sub.Corpus, Total.Tokens, Total.Files, Average.Tokens.Per.File) %>%
  pivot_longer(-Sub.Corpus, names_to = "Metric", values_to = "Value") %>%
  mutate(Metric = recode(Metric,
                         Total.Tokens = "Total Tokens",
                         Total.Files = "Total Files",
                         Average.Tokens.Per.File = "Average Tokens per File")) %>%
  pivot_wider(names_from = Sub.Corpus, values_from = Value)


wide_table %>%
  gt() %>%
  fmt_number(columns = -Metric, decimals = 2, use_seps = TRUE) %>%
  cols_label(Metric = "") %>%
  tab_header(
    title = md("**Table 1**"),
    subtitle = md("_ICNALE Sub-corpora_")
  ) %>%
  tab_options(
    table.font.size = 12,
    heading.align = "left",
    table.align = "center"
  )
```