---
title: "Prompt Distribution"
author: "Sitler"
date: "2025-05-02"
output: word_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(ggplot2)
library(forcats)
library(dplyr)

lb_data <- read.csv("LB.csv", header = TRUE)

lb_data <- lb_data %>%
    mutate(sub_corpus = fct_relevel(sub_corpus, "J-WE", "J-SM", "ENS-WE", "ENS-SM"))

prompt_dis <- lb_data[, c("sub_corpus", "frequency", "prompt_based_bundle")]
```


```{r}
custom_theme <- theme_minimal(base_family = "Times New Roman") +
  theme(
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white", color = NA),
    plot.background = element_rect(fill = "white", color = NA),
    axis.ticks.length = unit(0, "pt"),
    text = element_text(size = 15, color = "black"),
    axis.title = element_text(size = 15),
    axis.text = element_text(size = 15),
    legend.text = element_text(size = 15),
    legend.title = element_text(size = 15),
    axis.line = element_blank(),
    legend.position = "bottom",
    panel.border = element_blank(),
    panel.spacing = unit(0, "pt")
  )


plot_final <- ggplot(prompt_dis, aes(x = sub_corpus, y = frequency, fill = prompt_based_bundle)) +
  geom_col(position = "fill", width = 0.8, color = NA, linewidth = 0) +
  labs(x = "Sub-corpora", y = "Frequency", fill = NULL) +
  scale_y_continuous(labels = scales::percent, expand = c(0, 0)) +
  scale_fill_manual(
    values = c("orange", "blue", "darkgreen"),
    labels = c("Non-Prompt-Based", "Prompt-Based")
  ) +
  custom_theme

plot_final


```